# Generated by Django 5.1.1 on 2024-11-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VoiceText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word1", models.CharField(blank=True, max_length=100, null=True)),
                ("word2", models.CharField(blank=True, max_length=100, null=True)),
                ("word3", models.CharField(blank=True, max_length=100, null=True)),
                ("word4", models.CharField(blank=True, max_length=100, null=True)),
                ("word5", models.CharField(blank=True, max_length=100, null=True)),
                ("word6", models.CharField(blank=True, max_length=100, null=True)),
                ("word7", models.CharField(blank=True, max_length=100, null=True)),
                ("word8", models.CharField(blank=True, max_length=100, null=True)),
                ("word9", models.CharField(blank=True, max_length=100, null=True)),
                ("word10", models.CharField(blank=True, max_length=100, null=True)),
                ("word11", models.CharField(blank=True, max_length=100, null=True)),
                ("word12", models.CharField(blank=True, max_length=100, null=True)),
                ("word13", models.CharField(blank=True, max_length=100, null=True)),
                ("word14", models.CharField(blank=True, max_length=100, null=True)),
                ("word15", models.CharField(blank=True, max_length=100, null=True)),
                ("word16", models.CharField(blank=True, max_length=100, null=True)),
                ("word17", models.CharField(blank=True, max_length=100, null=True)),
                ("word18", models.CharField(blank=True, max_length=100, null=True)),
                ("word19", models.CharField(blank=True, max_length=100, null=True)),
                ("word20", models.CharField(blank=True, max_length=100, null=True)),
                ("word21", models.CharField(blank=True, max_length=100, null=True)),
                ("word22", models.CharField(blank=True, max_length=100, null=True)),
                ("word23", models.CharField(blank=True, max_length=100, null=True)),
                ("word24", models.CharField(blank=True, max_length=100, null=True)),
                ("word25", models.CharField(blank=True, max_length=100, null=True)),
                ("word26", models.CharField(blank=True, max_length=100, null=True)),
                ("word27", models.CharField(blank=True, max_length=100, null=True)),
                ("word28", models.CharField(blank=True, max_length=100, null=True)),
                ("word29", models.CharField(blank=True, max_length=100, null=True)),
                ("word30", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "voice_text",
            },
        ),
    ]
