# Generated by Django 5.1.3 on 2024-11-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_voicetext_options_remove_voicetext_word1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='VoiceText',
        ),
    ]
